version: '3.1'
services:
  web:
    build: ./ShipRegistry
    hostname: shipregistrysweb
    ports:
      - "5000:5000"
    environment:
      - BROKER=amqp://guest:guest@freightcaptain_broker:5672
      - Database__ShipRegistry=Server=freightcaptain_db;Uid=root;Pwd=root;Database=ShipRegistry
      - Database__ShipRegistryDb=Server=freightcaptain_db;Uid=root;Pwd=root
      - Database__MessageStore=Server=freightcaptain_db;Uid=root;Pwd=root;Database=ShipRegistry
      - Database__MessageTableName=Messages
    links:
      - rabbit:greetings_broker
      - mysql:greetings_db
    depends_on:
      - rabbit
      - mysql
 rabbit:
    image: rabbitmq:3-management
    hostname: freightcaptain_broker
    environment:
      - RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQG
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - "15672:15672"
      - "5672:5672"
  mysql:
    hostname: freightcaptain_db
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    healthcheck:
      test: mysqladmin ping -h localhost -p$$MYSQL_ROOT_PASSWORD && test '0' -eq $$(ps aux | awk '{print $$11}' | grep -c -e '^mysql$$')